### ISSUE TITLE
Destructuring-spread-attrs Doesn't have Title

### ISSUE THREAD

**Issue by lancesnider** [cht8687/React-ES5-To-ES6-Checklist#3]
All of the other paragraphs have a title saying the es version. This one, I'm assuming, is ES6, but doesn't say that anywhere. Also, is there not an ES5 equivalent?

**Comment by cht8687** [comment]
ye, this is a ES6 feature, I can't find any ES5 equivalent here, do you have any ideas?

**Comment by lancesnider** [comment]
I'm pretty new, sorry.

**Comment by cht8687** [comment]
@lancesnider  we learn together... :smile:
